### ISSUE TITLE
Bugs to Report for Inital Release-

### ISSUE THREAD

**Issue by NGCMaker** [Nintorch/Godotzilla#1]
I decided to give Godotzilla a go and use it, and it's pretty great! Following your tutorials does make it easier to work on and understand. However, I did find two bugs to report here. I also do have a suggestion.

Bugs:

- When shifting the board piece node for a new board or an existing board, when you enter in game, the icons will be shifted... but the "positions" won't be. So if I move Godzilla two tiles down, selecting the tile he seems to be on won't do anything, but going two tiles above somehow selects Godzilla, and lets you move him like a sort of ghost sprite. I'm aware that *probably* wasn't what the tutorial meant, but it doesn't go into detail on how to move it and not have it break in this way if I'm missing something.
- When you move to a transition level while a boss is next to said transition level, it will let you select if you wish to fight it or not. Then you proceed into the level and move on. But for some reason, the boss fight is skipped entirely, and when you get back to the board, the boss piece thinks you're still next to it even though your piece there is gone, so it just... never moves, resulting in a softlock. You might think this is an issue with having multiple transition levels, but if one assembles the end of the board in a V/X formation with the boss somehow next to it in a normal game, this softlock is very well possible.

Suggestion:

- The tutorial files are pretty good at going in depth for the most part, but as I said with moving the board pieces earlier, it's a little vague in certain areas. There should also be a tutorial for making new levels. I get it's probably relatively simple, but it's nice to have a tutorial on making new levels anyway, especially if there's certain common features people wish to add to their levels, like new enemies, minibosses, and cutscenes.

**Comment by Nintorch** [comment]
Thank you for the bug report and the suggestion!
Regarding the first bug, I'm not exactly sure how you're moving the node, can you provide a video that shows the issue, please?
Regarding the second bug, it's an interesting one, I didn't think of that possibility before, I will try to come up with a solution.
And regarding the suggestion, I didn't make a tutorial on how to make a new level for this exact reason (it's relatively simple) but now that I think about it, there are people with different amounts of Godot experience so it's probably good to have a tutorial that explains and suggests good practices on this topic. I will try to make it this week, and I will review other tutorials and try to make them less vague.

Thanks again!

**Comment by NGCMaker** [comment]
Here's the footage of the two bugs in action.

https://www.youtube.com/watch?v=c_ypuNaAdIA

https://www.youtube.com/watch?v=y-BP7_c3Gss

**Comment by Nintorch** [comment]
Sorry for taking so long :D
I've replayed GMoM and I think this is how it should work, so it doesn't immediately send the character to the next planet but rather the player themselves should explicitly state that the character needs to go there
I will try to fix the tutorials right now.

https://github.com/user-attachments/assets/cc6c42e9-5ba7-4424-ba01-b5aa3e4bda87

**Comment by Nintorch** [comment]
I've made the "board peice" parts of the new board and new character tutorials more clear by specifying that board pieces are the character objects on the board. You can check out the changes in the "wip" branch of the repository :)

**Comment by NGCMaker** [comment]
Great! Glad I could help.
